[build]
  publish = "exampleSite/public"

[build.environment]
  HUGO_VERSION = "0.109.0"
  HUGO_THEME = "repo"

[context.production]
  command = "cd exampleSite && hugo --gc --enableGitInfo --themesDir ../.. -b ${URL}"
  [context.production.environment]
    HUGO_ENV = "production"

[plugins.inputs]
  # If it should show more verbose logs (optional, default = true)
  debug = true
  # Relative path to source directory in case you use Hugo's "--s" option
  srcdir = "exampleSite"
