languageCode = 'en-us'
MetaDataFormat = "yaml"
title = 'Hugo Cosmos'
enableGitInfo = true
enableRobotsTXT = true
theme = "hugo-theme-cosmos"
baseURL = "https://hugo-theme-cosmos.netlify.app/"

[menu]
  [[menu.main]]
    title = "documentation"
    name = "book"
    url = "/docs/"
    weight = -50
  [[menu.main]]
    title = "garden"
    name = "brain"
    url = "/garden/"
    weight = -40
  [[menu.main]]
    title = "github"
    name = "github"
    url = "https://github.com/librabyte/hugo-theme-cosmos"
    weight = -30
  [[menu.main]]
    title = "rss"
    name = "rss"
    url = "/index.xml"
    weight = -20


[markup]
  [markup.highlight]
    style = 'monokai'
    codeFences = true
    guessSyntax = false
    lineNoStart =1
    lineNos = true
    lineNumbersInTable = true

  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2

  [markup.goldmark.renderer]
    unsafe = true


[module]
  [module.mounts]
    source = 'assets'
    target = 'assets'


[params]
  since = "2019"
  dateFormat = "January 2, 2006"

  enableHomeProfile = false
  mainSections = ["posts"]
  bookSection = "docs"
  photoSwipe = false

  # (Optional, default false) Enables search function with fuse.js.
  search = true
  # (Optional, default true) Display a "Back to top" link in the site footer.
  back2top = true
  # (Optional, default true) Enable douban short code for douban music/book reference.
  douban = true
  # (Optional, default true) Enable Table of Contents in the right sidebar.
  toc = true
  # (Optional, default true) always collapse in the file tree mode.
  alwaysCollapse = true

  # (Optional, default false) enable wikilink feature.
  [params.wikilink]
    enableWikilink = true
    enableBacklinks = true
    enableLinkPreview = false

  # (Optional, default true) Enable giscus as comment plugin.
  [params.comments.giscuss]
    enable = true
    repo = "librabyte/hugo-theme-cosmos"
    repoId = "R_kgDOIEDNvg"
    category = "Announcements"
    categoryId = "DIC_kwDOIEDNvs4CTiKG"
    theme = "light"

  [params.reward]
    enable = true
    [params.reward.items]
      wechat = "https://cosmos-1251905798.cos.ap-beijing.myqcloud.com/theme/wechatpay.png"
      alipay = "https://cosmos-1251905798.cos.ap-beijing.myqcloud.com/theme/alipay.jpg"

  [params.copyright]
    # (Optional, default true) Enable copyright info display in the post footer.
    enable = true
    content = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
    [params.copyright.gitInfo]
      gitRepo = "https://github.com/librabyte/hugo-theme-cosmos"
      showCommitMessage = true

  [params.markmap]
    enable = true

  [params.mermaid]
    enable = true

  [params.echarts]
    # enable/disable ECharts support
    enable = true
    map = true

  [params.katex]
    # enable/disable KaTeX support
    enable = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5
